In [3]:
import torch
from torch import nn
from torch import functional as F

In [9]:
torch.save([1,2,3],'sample')
#x,*y=torch.load('sample')

In [10]:
torch.load('sample')

[1, 2, 3]

In [12]:
class MLP(nn.Module):
    def __init__(self,inp,out):
        super().__init__()
        self.hidden=nn.Linear(inp,100)
        self.output=nn.Linear(100,out)

    def forward(self,X):
        return self.output(self.hidden(X))
X=torch.rand(20,40)
mlp=MLP(X.shape[1],4)

In [13]:
mlp(X)

tensor([[ 0.0262,  0.0755,  0.0100, -0.2003],
        [-0.0939,  0.1170,  0.0023, -0.1048],
        [-0.0156,  0.0854, -0.0961, -0.0451],
        [-0.0245,  0.1283, -0.0559, -0.0979],
        [ 0.0823,  0.1685,  0.0004, -0.0433],
        [-0.0436,  0.1487, -0.1331, -0.0797],
        [-0.1974, -0.0297, -0.0534, -0.0904],
        [ 0.1479,  0.0772, -0.0700,  0.0047],
        [-0.0741,  0.1196, -0.0597, -0.1230],
        [-0.0371,  0.0685,  0.0728, -0.2414],
        [ 0.0680,  0.2262, -0.0767, -0.0692],
        [-0.0162,  0.0861, -0.0844, -0.1389],
        [-0.0697,  0.0732, -0.0663, -0.0532],
        [-0.0589,  0.1809,  0.0007, -0.1672],
        [-0.1238,  0.1834, -0.0145, -0.1695],
        [-0.2688,  0.1709, -0.0535, -0.2369],
        [-0.0946, -0.0067,  0.0348, -0.2858],
        [ 0.0973,  0.1824, -0.0879, -0.1052],
        [-0.0388,  0.1627, -0.0472, -0.2041],
        [-0.0851, -0.0783, -0.0490, -0.1380]], grad_fn=<AddmmBackward>)

In [20]:
mlp.state_dict()['hidden.weight']


tensor([[-0.0114,  0.0329,  0.1264,  ...,  0.0503,  0.0674, -0.1545],
        [-0.0255, -0.1567, -0.1466,  ...,  0.0617, -0.0310,  0.0956],
        [-0.0862,  0.1426,  0.0321,  ..., -0.0929, -0.1542,  0.0736],
        ...,
        [-0.1523,  0.0114, -0.0294,  ...,  0.0353, -0.0741,  0.1577],
        [-0.1484, -0.0328, -0.1318,  ..., -0.0271,  0.0238,  0.0338],
        [-0.0711,  0.0391,  0.0836,  ..., -0.1271, -0.0544, -0.0308]])

In [21]:
torch.save(mlp.state_dict(),'mlp-params')

In [22]:
clone=MLP(X.shape[1],4)
clone.load_state_dict(torch.load('mlp-params'))

<All keys matched successfully>

In [23]:
clone.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.0114,  0.0329,  0.1264,  ...,  0.0503,  0.0674, -0.1545],
                      [-0.0255, -0.1567, -0.1466,  ...,  0.0617, -0.0310,  0.0956],
                      [-0.0862,  0.1426,  0.0321,  ..., -0.0929, -0.1542,  0.0736],
                      ...,
                      [-0.1523,  0.0114, -0.0294,  ...,  0.0353, -0.0741,  0.1577],
                      [-0.1484, -0.0328, -0.1318,  ..., -0.0271,  0.0238,  0.0338],
                      [-0.0711,  0.0391,  0.0836,  ..., -0.1271, -0.0544, -0.0308]])),
             ('hidden.bias',
              tensor([ 0.1169, -0.0030,  0.1291,  0.0432,  0.1412,  0.0682,  0.0129,  0.0167,
                       0.0455, -0.0320,  0.0596,  0.0442,  0.1100,  0.1285, -0.0406, -0.0691,
                      -0.0962, -0.1125, -0.0243,  0.0440,  0.0859, -0.1517,  0.0319,  0.1199,
                      -0.1033,  0.0704, -0.0338,  0.0428,  0.0471, -0.0376, -0.0718, -0.1216,
                       0.0098,

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
